#!/bin/bash
#!/bin/bash
RED="$(printf '\033[31m')"  
GREEN="$(printf '\033[32m')"  
ORANGE="$(printf '\033[33m')"  
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  
CYAN="$(printf '\033[36m')"  
WHITE="$(printf '\033[37m')" 
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  
GREENBG="$(printf '\033[42m')"  
ORANGEBG="$(printf '\033[43m')"  
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  
CYANBG="$(printf '\033[46m')" 
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
echo $BLUE"[1] Debian OS(Kali , Ubuntu)"$RESETBG
echo $BLUE"[2] Termux"$RESETBG
read -p $GREEN"Choose According to you: "$RESETBG opt
case $opt in
1)
sudo apt install python python3
pip3 install phonenumbers
clear
python3 track_phone.py
;;
2)
apt install python python3
pip3 install phonenumbers
clear
python3 track_phone.py
;;
*)
echo $RED"It seems you entered wrong input"$RESETBG 
echo " Try again Aborting..."
;;
esac